minsal_si_gminsal_sig_homepage:
    pattern:  /index
    defaults: { _controller: minsalSIGminsalSIGBundle:Login:index }
minsal_si_gminsal_sig_cerrar:
    pattern:  /cerrar
    defaults: { _controller: minsalSIGminsalSIGBundle:Login:index }
minsal_si_gminsal_sig_consultarUsuario:
    pattern:  /consultarUsuario
    defaults: { _controller: minsalSIGminsalSIGBundle:Usuario:Consultar }
minsal_si_gminsal_sig_InsertarUsuario:
    pattern:  /InsertarUsuario
    defaults: { _controller: minsalSIGminsalSIGBundle:Usuario:Insertar }
minsal_si_gminsal_sig_ModificarUsuario:
    pattern:  /ModificarUsuario/{id}
    defaults: { _controller: minsalSIGminsalSIGBundle:Usuario:Modificar }
minsal_si_gminsal_sig_EliminarUsuario:
    pattern:  /EliminarUsuario/{id}
    defaults: { _controller: minsalSIGminsalSIGBundle:Usuario:Eliminar }
minsal_si_gminsal_sig_consultarCargo:
    pattern:  /consultarCargo
    defaults: { _controller: minsalSIGminsalSIGBundle:Cargo:Consultar }
minsal_si_gminsal_sig_insertarCargo:
    pattern:  /insertarCargo
    defaults: { _controller: minsalSIGminsalSIGBundle:Cargo:Insertar }
minsal_si_gminsal_sig_modificarCargo:
    pattern:  /modificarCargo/{idCargo}
    defaults: { _controller: minsalSIGminsalSIGBundle:Cargo:Modificar }
minsal_si_gminsal_sig_eliminarCargo:
    pattern:  /eliminarCargo/{idCargo}
    defaults: { _controller: minsalSIGminsalSIGBundle:Cargo:Eliminar }
minsal_si_gminsal_sig_consultarEmpleado:
    pattern:  /consultarEmpleado
    defaults: { _controller: minsalSIGminsalSIGBundle:Empleado:Consultar }
minsal_si_gminsal_sig_InsertarEmpleado:
    pattern:  /InsertarEmpleado
    defaults: { _controller: minsalSIGminsalSIGBundle:Empleado:Insertar }
minsal_si_gminsal_sig_ModificarEmpleado:
    pattern:  /ModificarUsuario/{idEmpleado}
    defaults: { _controller: minsalSIGminsalSIGBundle:Empleado:Modificar }
minsal_si_gminsal_sig_EliminarEmpleado:
    pattern:  /EliminarEmpleado/{idEmpleado}
    defaults: { _controller: minsalSIGminsalSIGBundle:Empleado:Eliminar }
minsal_si_gminsal_sig_cum:
    pattern:  /cum
    defaults: { _controller: minsalSIGminsalSIGBundle:MejorCum:MejorCum }
minsal_si_gminsal_sig_plazas:
    pattern:  /plazas
    defaults: { _controller: minsalSIGminsalSIGBundle:Plazas:Plazas }
minsal_si_gminsal_sig_pruebaCon:
    pattern:  /pruebaCon
    defaults: { _controller: minsalSIGminsalSIGBundle:PruebaCon:PruebaCon }
minsal_si_gminsal_sig_aprobados:
    pattern:  /aprobados
    defaults: { _controller: minsalSIGminsalSIGBundle:Aprobados:Aprobados }
minsal_si_gminsal_sig_distribucion:
    pattern:  /distribucion
    defaults: { _controller: minsalSIGminsalSIGBundle:Distribucion:Distribucion }
minsal_si_gminsal_sig_informefinal:
    pattern:  /informefinal
    defaults: { _controller: minsalSIGminsalSIGBundle:Informefinal:Informefinal }
minsal_si_gminsal_sig_conplazas:
    pattern:  /conplazas
    defaults: { _controller: minsalSIGminsalSIGBundle:ConsolidadoPlaza:ConsolidadoPlaza }
minsal_si_gminsal_sig_estudiantes:
    pattern:  /estudiantes
    defaults: { _controller: minsalSIGminsalSIGBundle:Estudiantes:Estudiantes }
minsal_si_gminsal_sig_montoTotal:
    pattern:  /montoTotal
    defaults: { _controller: minsalSIGminsalSIGBundle:MontoTotal:MontoTotal }
minsal_si_gminsal_sig_promPrueba:
    pattern:  /promPrueba
    defaults: { _controller: minsalSIGminsalSIGBundle:PromPrueba:PromPrueba }
minsal_si_gminsal_sig_rangoNotas:
    pattern:  /rangoNotas
    defaults: { _controller: minsalSIGminsalSIGBundle:RangoNotas:RangoNotas }
minsal_si_gminsal_sig_conTodos1:
    pattern:  /todos1
    defaults: { _controller: minsalSIGminsalSIGBundle:MejorCum:todos }
minsal_si_gminsal_sig_rep2_tact_todo:
    pattern:  /rep2
    defaults: { _controller: minsalSIGminsalSIGBundle:PruebaCon:todos }
